image: node:latest

stages:
  - build
  - test

build:
  stage: build
  except:
    - master
  script:
    - npm install
    - npm run-script build

test:
  stage: test
  except:
    - master
  script:
    - npm install
    - npm test