image: node:latest

stages:
  - test
  - clean

test:
  stage: test
  except:
    - master
  script:
    - npm install
    - npm test
  cache:
    paths:
      - node_modules/

clean:
  stage: clean
  except:
    - master
  script:
    - rm -rf node_modules/
  cache:
    paths:
      - node_modules/